export enum HideawayActions {
  ADD_HIDEAWAY_SIMPLE = 'ADD_HIDEAWAY_SIMPLE',
  ADD_HIDEAWAY_THUNK = 'ADD_HIDEAWAY_THUNK',
  ADD_HIDEAWAY_SIMPLE_STATE = 'ADD_HIDEAWAY_SIMPLE_STATE',
  ADD_HIDEAWAY_THUNK_STATE = 'ADD_HIDEAWAY_THUNK_STATE',
  ADD_HIDEAWAY_SIMPLE_MULTILEVEL = 'ADD_HIDEAWAY_SIMPLE_MULTILEVEL',
  ADD_HIDEAWAY_THUNK_MULTILEVEL = 'ADD_HIDEAWAY_THUNK_MULTILEVEL',
  ADD_HIDEAWAY_SIMPLE_MULTILEVEL_STATE = 'ADD_HIDEAWAY_SIMPLE_MULTILEVEL_STATE',
  ADD_HIDEAWAY_THUNK_MULTILEVEL_STATE = 'ADD_HIDEAWAY_THUNK_MULTILEVEL_STATE',
  ADD_HIDEAWAY_NESTED_STATE = 'ADD_HIDEAWAY_NESTED_STATE',
}
