export enum HideawayActions {
  ADD_SIMPLE_HIDEAWAY = 'ADD_SIMPLE_HIDEAWAY',
  ADD_SIMPLE_HIDEAWAY_STATE = 'ADD_SIMPLE_HIDEAWAY_STATE',
  ADD_HIDEAWAY_STRING = 'ADD_HIDEAWAY_STRING',
  ADD_HIDEAWAY_STATE_STRING = 'ADD_HIDEAWAY_STATE_STRING',
}
